const nd_din = [
[[1,35,'—'],[36,75,'1d6x10 TC'],[76,100,'1d4x100 TC']],
[[1,30,'—'],[31,75,'1d6x100 TC'],[76,100,'2d4x10 T$']],
[[1,25,'—'],[26,75,'2d6x100 TC'],[76,100,'2d8x10 T$']],
[[1,20,'—'],[21,70,'3d8x10 T$'],[71,95,'4d12x10 T$'],[96,100,'1 riqueza menor']],
[[1,15,'—'],[16,55,'3d10x10 T$'],[56,85,'2d4x100 T$'],[86,95,'2d6+1x100 T$'],[96,100,'1 riqueza menor']],
[[1,10,'—'],[11,20,'4d12x10 T$'],[21,60,'1d4x100 T$'],[61,90,'1d8x10 TO'],[91,100,'1d3 riquezas menores']],
[[1,10,'—'],[11,50,'1d6x100 T$'],[51,80,'1d12x100 T$'],[81,90,'1 riqueza menor*'],[91,100,'1d3 riquezas menores*']],
[[1,15,'—'],[16,65,'1d8x100 T$'],[66,95,'3d4x10 TO'],[96,100,'1 riqueza média']],
[[1,15,'—'],[16,60,'2d6x100 T$'],[61,90,'2d10x100 T$'],[91,100,'1d3+1 riquezas menores']],
[[1,10,'—'],[11,60,'2d8x100 T$'],[61,90,'2d12x10 TO'],[91,100,'1d4+1 riquezas menores']],
[[1,10,'—'],[11,55,'2d10x100 T$'],[56,95,'1d4+1 riquezas menores'],[96,100,'1 riqueza média*']],
[[1,10,'—'],[11,35,'1 riqueza média'],[36,85,'4d6x100 T$'],[86,100,'1d3 riquezas médias']],
[[1,10,'—'],[11,30,'4d6x100 T$'],[31,85,'4d10x10 TO'],[86,100,'1d3+1 riquezas médias']],
[[1,10,'—'],[11,45,'2d4x1000 T$'],[46,85,'1d3 riquezas médias'],[86,100,'2d6x100 TO']],
[[1,10,'—'],[11,45,'1 riqueza média*'],[46,80,'2d6x1000 T$'],[81,100,'1d4+1 riquezas médias']],
[[1,10,'—'],[11,45,'4d4x1000 T$'],[46,80,'1d3+1 riquezas médias'],[81,100,'4d6x100 TO']],
[[1,10,'—'],[11,45,'1d3+1 riquezas médias'],[46,80,'3d6x1000 T$'],[81,100,'1 riqueza maior']],
[[1,10,'—'],[11,45,'1 riqueza média*'],[46,80,'2d10x1000 T$'],[81,100,'1d4x1000 TO']],
[[1,10,'—'],[11,40,'3d6x1000 T$'],[41,75,'3d10x100 TO'],[76,100,'1d3 riquezas maiores']],
[[1,5,'—'],[6,40,'4d6x1000 T$'],[41,75,'1d3 riquezas médias*'],[76,100,'2d4x1000 TO']],
[[1,5,'—'],[6,40,'4d10x1000 T$'],[41,75,'1 riqueza maior'],[76,100,'1d3+1 riquezas maiores']],
[[1,5,'—'],[6,40,'4d12x1000 T$'],[41,75,'1 riqueza maior*'],[76,100,'1d12x1000 TO']],
[[1,5,'—'],[6,40,'2d4x1000 TO'],[41,75,'1d3 riquezas maiores'],[76,100,'1d3+1 riquezas maiores*']]
];

const nd_item = [
[[1,50,'—'],[51,80,'Diverso'],[81,100,'Equipamento']],
[[1,50,'—'],[51,75,'Diverso'],[76,100,'Equipamento']],
[[1,45,'—'],[46,70,'Diverso'],[71,100,'Equipamento']],
[[1,40,'—'],[41,65,'Diverso'],[66,90,'Equipamento'],[91,100,'1 poção']],
[[1,30,'—'],[31,40,'Diverso'],[41,70,'Equipamento'],[71,90,'1 poção'],[91,100,'Superior (1 melhoria)']],
[[1,25,'—'],[26,35,'Diverso'],[36,60,'Equipamento'],[61,85,'1 poção'],[86,100,'Superior (1 melhoria)']],
[[1,20,'—'],[21,30,'Diverso'],[31,55,'Equipamento'],[56,80,'1 poção*'],[81,100,'Superior (1 melhoria)']],
[[1,20,'—'],[21,70,'1 poção'],[71,90,'Superior (1 melhoria)'],[91,100,'Superior (2 melhorias)']],
[[1,20,'—'],[21,65,'1 poção*'],[66,95,'Superior (1 melhoria)'],[96,100,'Superior (2 melhorias)']],
[[1,20,'—'],[21,60,'1d3 poções'],[61,90,'Superior (2 melhorias)'],[91,100,'Superior (3 melhorias)']],
[[1,20,'—'],[21,75,'1d3 poções'],[76,95,'Superior (2 melhorias)'],[96,100,'Superior (3 melhorias)']],
[[1,20,'—'],[21,70,'1 poção*'],[76,95,'Superior (3 melhorias)'],[96,100,'Mágico (menor)']],
[[1,50,'—'],[51,75,'1d3+1 poções'],[76,90,'Superior (3 melhorias)'],[91,100,'Mágico (menor)']],
[[1,45,'—'],[46,70,'1d4+1 poções'],[71,90,'Superior (3 melhorias)'],[91,100,'Mágico (menor)']],
[[1,45,'—'],[46,70,'1d3+1 poções*'],[71,85,'Superior (4 melhorias)'],[86,100,'Mágico (menor)']],
[[1,40,'—'],[41,65,'1d4+1 poções*'],[66,95,'Superior (4 melhorias)'],[96,100,'Mágico (médio)']],
[[1,40,'—'],[41,65,'1d4+1 poções*'],[66,85,'Superior (4 melhorias)'],[91,100,'Mágico (médio)']],
[[1,35,'—'],[36,45,'1d6+1 poções'],[46,85,'Superior (4 melhorias)'],[86,100,'Mágico (médio)']],
[[1,35,'—'],[36,45,'1d6+1 poções*'],[46,80,'Superior (4 melhorias)'],[81,100,'Mágico (médio)']],
[[1,20,'—'],[21,40,'Mágico (menor)'],[41,80,'Mágico (médio)'],[81,100,'Mágico (maior)']],
[[1,15,'—'],[16,40,'Mágico (menor)'],[41,70,'Mágico (médio)'],[71,100,'Mágico (maior)']],
[[1,10,'—'],[11,40,'Mágico (menor)'],[41,60,'Mágico (médio)'],[61,100,'Mágico (maior)']],
[[1,5,'—'],[6,40,'Mágico (menor)'],[41,50,'Mágico (médio)'],[51,100,'Mágico (maior)']]
];

const riquezas = [
[1,25,-1,-1,-1,-1,'4d4x1','ágata (½); hematita (½); barril de farinha (5); gaiola com galinhas (5)'],
[26,40,-1,-1,-1,-1,'1d4x10','quartzo rosa (½); topázio (½); caixa de tabaco (1); rolo de linho (1); jarro de especiarias, como canela, gorad, pimenta ou sal (2)'],
[41,55,1,10,-1,-1,'2d4x10','bracelete de ouro finamente trabalhado (½); estatueta de osso (1); estatueta de marfim entalhado (1); rolo de seda (1); vaso de prata (2)'],
[56,70,11,30,-1,-1,'4d6x10','ametista (½); pérola branca (½); lingote de prata (1); cálice de prata com gemas de lápis-lazúli (1); tapeçaria grande e bem-feita de lã (5)'],
[71,85,31,50,1,5,'1d6x100','alexandrita (½); pérola negra (½); espada cerimonial ornada com prata e gema negra no cabo (1); pente de prata com pedras preciosas (1)'],
[86,95,51,65,6,15,'2d6x100','pente em forma de dragão com olhos de gema vermelha (1); harpa de madeira exótica com omamentos de zircâo e marfim (5).'],
[96,99,66,80,16,25,'2d8x100','opala negra (½); tapa-olho com um olho falso de safira (½); luva bordada e adornada com gemas (1); pingente de opala vermelha com corrente de ouro (1); lingote de ouro (2); pintura antiga (2)'],
[100,100,81,90,26,40,'4d10x100','esmeralda verde (½); pingente de safira (½); caixinha de música de ouro (1); tornozeleira com gemas (1); manto bordado em veludo e seda com inúmeras pedras preciosas (2)'],
[101,101,91,95,41,60,'6d12x100','anel de prata e safira (½); correntinha com pequenas pérolas rosas (½); diamante branco (½); ídolo de ouro puro maciço (5)'],
[101,101,96,99,61,75,'2d10x1000','anel de ouro e rubi (½); diamante vermelho (½); conjunto de taças de ouro decoradas com esmeraldas (2)'],
[101,101,100,100,76,85,'6d8x1000','coroa de ouro adornada com centenas de gemas, pertencente a um antigo monarca (1); baú de mitral com coleção de diamantes (2)'],
[101,101,101,101,86,95,'1d10x10000','arca de madeira reforçada repleta de lingotes de prata e ouro, além de pedras preciosas de vários tipos (20)'],
[101,101,101,101,96,100,'4d12x10000','sala forrada de moedas! Mover todo esse dinheiro exige trabalhadores e carroças (ou outra ideia por parte dos jogadores), além de atrair a atenção de bandidos, coletores de impostos e aproveitadores de vários tipos...'],
];

const pocoes = [
    [1,1,'óleo','Abençoar Alimentos','',30,1],
    [2,3,'granada','Área Escorregadia','',30,1],
    [4,6,'óleo','Arma Mágica','',30,1],
    [7,7,'poção','Compreensão','',30,1],
    [8,15,'poção','Curar Ferimentos','recuperação 2d8+2 PV',30,1],
    [16,18,'poção','Disfarce Ilusório','',30,1],
    [19,20,'óleo','Escuridão','',30,1],
    [21,22,'óleo','Luz','',30,1],
    [23,24,'granada','Névoa','',30,1],
    [25,26,'poção','Primor Atlético','',30,1],
    [27,28,'poção','Proteção Divina','',30,1],
    [29,30,'poção','Resistência a Energia','',30,1],
    [31,32,'poção','Sono','',30,1],
    [33,33,'poção','Suporte Ambiental','',30,1],
    [34,34,'óleo','Tranca Arcana','',30,1],
    [35,35,'poção','Visão Mística','',30,1],
    [36,36,'poção','Vitalidade Fantasma','',30,1],
    [37,38,'poção','Escudo da Fé','duração cena',120,2],
    [39,40,'poção','Alterar Tamanho','',270,3],
    [41,42,'poção','Aparência Perfeita','',270,3],
    [43,43,'óleo','Armamento da Natureza','',270,1],
    [44,49,'granada','Bola de Fogo','',270,3],
    [50,51,'poção','Camuflagem ilusória','',270,3],
    [52,53,'poção','Concentração de Combate','duração cena',270,3],
    [54,62,'poção','Curar Ferimentos','recuperação 4d8+4 PV',270,3],
    [63,66,'poção','Físico Divino','',270,3],
    [67,68,'poção','Mente Divina','',270,3],
    [69,70,'poção','Metamorfose','',270,3],
    [71,75,'poção','Purificação','',270,3],
    [76,77,'poção','Velocidade','',270,3],
    [78,79,'óleo','Vestimenta da Fé','',270,3],
    [80,80,'poção','Voz Divina','',270,3],
    [81,82,'óleo','Arma Mágica','bônus +3',750,5],
    [83,88,'poção','Curar Ferimentos','recuperação 7d8+7 PV',1080,6],
    [89,89,'poção','Físico Divino','três atributos',1080,6],
    [90,92,'poção','Invisibilidade','duração cena',1080,6],
    [93,96,'granada','Bola de Fogo','10d6 de dano',1470,7],
    [97,100,'poção','Curar Ferimentos','recuperação 11d8+11 PV',3000,10]
];

const diverso = [
    [1,2,'Ácido'],
    [3,4,'Agua benta'],
    [5,5,'Alaúde élfico'],
    [6,6,'Algemas'],
    [7,8,'Baga-de-fogo'],
    [9,23,'Bálsamo restaurador'],
    [24,24,'Bandana'],
    [25,25,'Bandoleira de poções'],
    [26,30,'Bomba'],
    [31,31,'Botas reforçadas'],
    [32,32,'Camisa bufante'],
    [33,33,'Capa esvoaçante'],
    [34,34,'Capa pesada'],
    [35,35,'Casaco longo'],
    [36,36,'Chapéu arcano'],
    [37,38,'Coleção de livros'],
    [39,40,'Cosmético'],
    [41,42,'Dente-de-dragão'],
    [43,43,'Enfeite de elmo'],
    [44,44,'Elixir do amor'],
    [45,46,'Equipamento de viagem'],
    [47,56,'Essência de mana'],
    [57,57,'Estojo de disfarces'],
    [58,58,'Farrapos de ermitão'],
    [59,59,'Flauta mística'],
    [60,66,'Fogo alquímico'],
    [67,67,'Gorro de ervas'],
    [68,69,'Líquen lilás'],
    [70,70,'Luneta'],
    [71,71,'Luva de pelica'],
    [72,73,'Maleta de medicamentos'],
    [74,74,'Manopla'],
    [75,75,'Manto eclesiástico'],
    [76,78,'Mochila de aventureiro'],
    [79,80,'Musgo púrpura'],
    [81,81,'Organizador de pergaminhos'],
    [82,83,'Ossos de monstro'],
    [84,85,'Pó de cristal'],
    [86,87,'Pó de giz'],
    [88,88,'Pó do desaparecimento'],
    [89,89,'Robe de mago'],
    [90,91,'Saco de sal'],
    [92,92,'Sapatos de camurça'],
    [93,94,'Seixo de âmbar'],
    [95,95,'Sela'],
    [96,96,'Tabardo'],
    [97,98,'Terra de cemitério'],
    [99,99,'Veste de seda'],
    [100,100,'Veste da corte']
];

const arma = [
    [1,3,'Adaga'],
    [4,5,'Alabarda'],
    [6,7,'Alfange'],
    [8,10,'Arco curto'],
    [11,13,'Arco longo'],
    [14,15,'Azagaia'],
    [16,16,'Balas (20)'],
    [17,18,'Besta leve'],
    [19,20,'Besta pesada'],
    [21,23,'Bordão'],
    [24,24,'Chicote'],
    [25,27,'Cimitarra'],
    [28,30,'Clava'],
    [31,31,'Corrente de espinhos'],
    [32,33,'Espada bastarda'],
    [34,38,'Espada curta'],
    [39,43,'Espada longa'],
    [44,46,'Flechas (20)'],
    [47,49,'Florete'],
    [50,51,'Foice'],
    [52,53,'Funda'],
    [54,55,'Gadanho'],
    [56,56,'Katana'],
    [57,59,'Lança'],
    [60,60,'Lança montada'],
    [61,63,'Maça'],
    [64,66,'Machadinha'],
    [67,67,'Machado anão'],
    [68,70,'Machado de batalha'],
    [71,73,'Machado de guerra'],
    [74,74,'Machado táurico'],
    [75,76,'Mangual'],
    [77,77,'Manopla'],
    [78,80,'Martelo de guerra'],
    [81,83,'Montante'],
    [84,84,'Mosquete'],
    [85,85,'Pedras (20)'],
    [86,88,'Picareta'],
    [89,90,'Pique'],
    [91,92,'Pistola'],
    [93,93,'Rede'],
    [94,96,'Tacape'],
    [97,98,'Tridente'],
    [99,100,'Virotes (20)']
];

const armadura = [
    [1,5,'Armadura de Couro'],
    [6,10,'Brunea'],
    [11,25,'Armadura Completa'],
    [26,30,'Cota de malha'],
    [31,45,'Couraça'],
    [46,55,'Couro Batido'],
    [56,65,'Escudo leve'],
    [66,80,'Escudo pesado'],
    [81,85,'Gibão de peles'],
    [86,90,'Loriga segmentada'],
    [91,100,'Meia armadura']
    ];

const esoterico = [
    [1,10,'Bolsa de pó'],
    [11,25,'Cajado arcano'],
    [26,35,'Cetro elemental'],
    [36,42,'Costela de lich'],
    [43,50,'Dedo de ente'],
    [51,55,'Luva de ferro'],
    [56,65,'Medalhão de prata'],
    [66,75,'Orbe cristalina'],
    [76,85,'Tomo hermético'],
    [86,100,'Varinha arcana']
];

const armas_sup = [
    [1,10,'Atroz',2,4,,'A arma é um amontoado de pontas, ganchos e protuberâncias. É dificil empunhá-la sem se machucar, mas ela fornece +2 nas rolagens de dano.','+2 nas rolagens de dano'],
    [11,13,'Banhada a ouro',1,'',,'Uma melhoria favorita de nobres pomposos ou de aventureiros que acabaram de enriquecer. Fornece +2 em Diplomacia. O mestre pode mudar o bônus para uma penalidade de -2 contra pessoas que desprezam ostentação. Além disso, pode atrair a cobiça de ladrões.','+2 em Diplomacia'],
    [14,23,'Certeira',1,'',,'Fabricada para ser mais precisa e balanceada, a arma fornece +1 nos testes de ataque.','+1 nos testes de ataque'],
    [24,26,'Cravejada de gemas',1,'',,'É fácil ser persuadido por alguém opulento o bastante para ostentar um item cravejado de gemas. Fornece +2 em Enganação. Assim como um item banhado a ouro, um item cravejado de gemas pode atrair a cobiça de ladrões.','+2 em Enganação'],
    [27,36,'Cruel',1,'',,'Rebarbas, espinhos e até mesmo lâminas adicionais compõem uma arma cruel. Ela fornece +1 nas rolagens de dano.','+1 nas rolagens de dano'],
    [37,39,'Discreta',1,'',,'O item é disfarçado como outro item inócuo (como um florete escondido em uma bengala) ou modificado para ser telescópico (podendo se dobrar em si mesmo para ocupar menos espaço). O item ocupa -1 espaço (mínimo 1) e fornece +5 em testes de Ladinagem para ser ocultado.','-1 espaço, +5 para ocultar'],
    [40,44,'Equilibrada',1,'',,'Uma arma equilibrada é forjada com o balanço perfeito, o que facilita movimentos complexos. Ela fornece +2 em testes de manobras (desarmar, quebrar etc.).','+2 em testes de manobras'],
    [45,48,'Harmonizada',1,'*',,'A arma foi banhada em óleos alquímicos que a deixaram sintonizada com a aura de seu usuário. Escolha uma habilidade ativada ao se fazer um ataque ou usar a ação agredir e que custe pontos de mana. Esta habilidade tem seu custo em PM reduzido em -1 se utilizada com esta arma.','Custo de habilidades de ataque diminui em -1 PM'],
    [49,53,'Injeção alquimica',1,'',,'Um minúsculo frasco de cerâmica ou vidro é inserido ao longo da arma, junto com um mecanismo injetor ativado por impacto. Um ataque que acerte causa seu dano normal e libera uma carga de um preparado (como ácido ou fogo alquímico) ou de água benta, que atinge o alvo automaticamente. A melhoria tem espaço para 2 doses. Recarregá-la exige urna ação completa e o gasto dos itens com os quais você quiser carregá-la.','Gera efeito de preparado'],
    [54,55,'Macabra',1,'',,'Um item macabro é pintado com sangue seco, esculpido na forma de uma caveira ou decorado com pedaços de orelhas, dedos e olhos. Essa aparência assustadora fornece +2 em testes de Intimidação, mas impõe uma penalidade de -2 em testes de Diplomacia.','+2 em Intimidação, -2 em Diplomacia'],
    [56,65,'Maciça',1,'',13,'A arma é feita com material denso, fazendo com que seus golpes tenham impacto terrível. O multiplicador de crítico da arma aumenta em 1 ponto. Uma arma não pode ser maciça e precisa.','+1 no multiplicador de crítico'],
    [66,75,'Material especial',1,'',,'Uma armadura, escudo ou item esotérico é feito de, ou banhado com, um material especial. Cada material fornece um beneficio, cumulativo com outros beneficios de melhorias, mas possui um preço adicional que deve ser pago além do preço da melhoria. Fabricar um item de material especial exige um trabalho mais complexo do que materiais comuns.','Conforme o material'],
    [76,80,'Mira telescópica',1,'',,'Aumenta o alcance da arma em uma categoria (de curto para médio, de médio para longo) e o alcance da habilidade Ataque Furtivo para médio. Esta melhoria só pode ser aplicada em armas de disparo (exceto fundas).','Aumenta alcance da arma'],
    [81,90,'Precisa',1,'',10,'Cuidado especial foi tomado ao temperar o aço desta arma, para que seu fio se mantenha sempre como uma navalha. A margem de ameaça aumenta em 1 ponto. Uma arma não pode ser precisa e maciça.','+1 na margem de ameaça'],
    [91,100,'Pungente',2,2,,'Temperada diversas vezes para adquirir o fio ou o equilíbrio perfeito, a arma fornece +2 nos testes de ataque.','+2 nos testes de ataque']
];
    
const armaduras_sup = [
    [1,15,'Ajustada',1,'',,'Feito com peças medidas com precisão, o item tem a sua penalidade de armadura diminuída em 1.','-1 na penalidade de armadura'],
    [16,19,'Banhada a ouro',1,'',,'Uma melhoria favorita de nobres pomposos ou de aventureiros que acabaram de enriquecer. Fornece +2 em Diplomacia. O mestre pode mudar o bônus para uma penalidade de -2 contra pessoas que desprezam ostentação. Além disso, pode atrair a cobiça de ladrões.','+2 em Diplomacia'],
    [20,23,'Cravejada de gemas',1,'',,'É fácil ser persuadido por alguém opulento o bastante para ostentar um item cravejado de gemas. Fornece +2 em Enganação. Assim como um item banhado a ouro, um item cravejado de gemas pode atrair a cobiça de ladrões.','+2 em Enganação'],
    [24,28,'Delicada',1,'',9,'Apenas os materiais mais leves foram usados nesta armadura. As placas têm a espessura mínima necessária para oferecer a proteção que devem. Esta melhoria só pode ser aplicada a armaduras pesadas e permite que o personagem aplique 1 ponto de sua Destreza na Defesa (ou de outro atributo, caso o utilize em vez de Des). Uma armadura não pode ser delicada e reforçada.','Aplica 1 ponto de Des na Defesa'],
    [29,32,'Discreta',1,'',,'O item é disfarçado como outro item inócuo (como um florete escondido em uma bengala) ou modificado para ser telescópico (podendo se dobrar em si mesmo para ocupar menos espaço). O item ocupa -1 espaço (mínimo 1) e fornece +5 em testes de Ladinagem para ser ocultado.','-1 espaço, +5 para ocultar'],
    [33,37,'Espinhos',1,'',,'Armaduras: Uma armadura coberta de espinhos é uma visão impressionante — principalmente se os espinhos estiverem banhados com o sangue dos inimigos! Se o usuário agarrar ou for agarrado por uma criatura, causa dano de perfuração nesta criatura igual a sua Força. O dano é causado quando a manobra é feita e no início de cada turno do personagem, enquanto ela for mantida.<br>Escudos: Aumenta o dano de um ataque com escudo em um passo.','Causa dano com agarrar ou aumenta dano do escudo'],
    [38,40,'Macabra',1,'',,'Um item macabro é pintado com sangue seco, esculpido na forma de uma caveira ou decorado com pedaços de orelhas, dedos e olhos. Essa aparência assustadora fornece +2 em testes de Intimidação, mas impõe uma penalidade de -2 em testes de Diplomacia.','+2 em Intimidação, -2 em Diplomacia'],
    [41,50,'Material especial',1,'',,'Uma armadura, escudo ou item esotérico é feito de, ou banhado com, um material especial. Cada material fornece um beneficio, cumulativo com outros beneficios de melhorias, mas possui um preço adicional que deve ser pago além do preço da melhoria. Fabricar um item de material especial exige um trabalho mais complexo do que materiais comuns.','Conforme o material'],
    [51,55,'Polida',1,'',,'Uma armadura ou escudo com esta melhoria foi feito com metais reluzentes. Além de ser bonita, a luz refletida ofusca inimigos. Em ambientes iluminados, o item tem seu bônus de Defesa aumentado em +5, mas apenas na primeira rodada de combate — após isso, os inimigos se acostumam ao reflexo.','+2 na Defesa na primeira rodada'],
    [56,80,'Reforçada',1,'',3,'Placas adicionais, uma camada extra de cota de malha ou acolchoamento, proteção dobrada nas juntas e áreas vulneráveis... O bônus na Defesa e a penalidade de armadura de uma armadura ou escudo com esta melhoria aumentam em 1. Uma armadura não pode ser reforçada e delicada.','+1 na Defesa, +1 na penalidade de armadura'],
    [81,90,'Selada',1,'',,'A armadura foi forjada de forma a proteger todo o corpo do usuário, sem deixar espaço para nem mesmo um alfinete! Esta melhoria fornece um bônus de +1 em testes de resistência, mas só pode ser aplicado em armaduras pesadas.','+1 nos testes de resistência'],
    [91,100,'Sob medida',2,'0',,'Embora muitas armaduras sejam feitas especificamente para um usuário, esta passou por um período extenso de ajustes e refinamento, adequando-se com perfeição ao seu corpo. Reduz a penalidade por armadura em 2, mas apenas para o usuário específico (para outros, comporta-se como um item ajustado).','-2 na penalidade de armadura']
];
    
const esotericos_sup = [
    [1,4,'Banhada a ouro',1,'',,'Uma melhoria favorita de nobres pomposos ou de aventureiros que acabaram de enriquecer. Fornece +2 em Diplomacia. O mestre pode mudar o bônus para uma penalidade de -2 contra pessoas que desprezam ostentação. Além disso, pode atrair a cobiça de ladrões.','+2 em Diplomacia'],
    [5,8,'Cravejada de gemas',1,'',,'É fácil ser persuadido por alguém opulento o bastante para ostentar um item cravejado de gemas. Fornece +2 em Enganação. Assim como um item banhado a ouro, um item cravejado de gemas pode atrair a cobiça de ladrões.','+2 em Enganação'],
    [9,12,'Discreto',1,'',,'O item é disfarçado como outro item inócuo (como um florete escondido em uma bengala) ou modificado para ser telescópico (podendo se dobrar em si mesmo para ocupar menos espaço). O item ocupa -1 espaço (mínimo 1) e fornece +5 em testes de Ladinagem para ser ocultado.','-1 espaço, +5 para ocultar'],
    [13,27,'Energético',1,'',,'Catalisadores alquímicos inseridos no item fazem com que ele potencialize energias mágicas. Suas magias que causam dano causam +1d6 pontos de dano do mesmo de tipo.','+1d6 no dano de magias'],
    [28,42,'Harmonizado',1,'',,'Escolha uma magia. Seu custo diminui em -1 PM. Você pode mudar a magia afetada pelo item com um ritual que exige um dia e T$ 100 em ingredientes.','Custo de uma magia diminui em -1 PM'],
    [43,45,'Macabra',1,'',,'Um item macabro é pintado com sangue seco, esculpido na forma de uma caveira ou decorado com pedaços de orelhas, dedos e olhos. Essa aparência assustadora fornece +2 em testes de Intimidação, mas impõe uma penalidade de -2 em testes de Diplomacia.','+2 em Intimidação, -2 em Diplomacia'],
    [46,54,'Material especial',1,'',,'Uma armadura, escudo ou item esotérico é feito de, ou banhado com, um material especial. Cada material fornece um beneficio, cumulativo com outros beneficios de melhorias, mas possui um preço adicional que deve ser pago além do preço da melhoria. Fabricar um item de material especial exige um trabalho mais complexo do que materiais comuns.','Conforme o material'],
    [55,70,'Poderoso',1,'',,'A CD para resistir a suas magias aumenta em +1.','+1 na CD de suas magias'],
    [71,85,'Potencializador',1,'',,'Uma gema mística inserida no item permite que você acumule mais mana do que normalmente seria capaz. O limite de PM que você pode gastar em magias aumenta em +1.','+1 no limite de PM'],
    [86,100,'Vigilante',1,'',,'O item usa parte de sua mana pessoal para gerar um campo que desvia ataques. Você recebe +2 em Defesa.','+2 em Defesa']
];

const mat_esp = [
    ['Aço Rubi','Quando faz um ataque, você pode pagar 1 PM para ignorar qualquer tipo de resistência ou imunidade a dano contra este ataque.','Fornece uma chance de ignorar o dano extra de acertos críticos e ataques furtivos: 25% (1 em 1d4). Esse efeito é cumulativo entre si.','Fornece uma chance de ignorar o dano extra de acertos críticos e ataques furtivos: 25% (1 em 1d4). Esse efeito é cumulativo entre si.','Fornece uma chance de ignorar o dano extra de acertos críticos e ataques furtivos: 50% (qualquer valor par em qualquer dado). Esse efeito é cumulativo entre si.','Permite que você pague +2 PM ao lançar uma magia para que ela ignore qualquer tipo de resistência ou imunidade a dano.','Este metal tem a aparência de vidro avermelhado, mas é duro como aço. Aço-rubi é caríssimo e comercializado apenas por uma guilda de ferreiros de Doherimm. Os anões mantém a origem deste material em segredo, mas suspeita-se de que ele seja minerado das profundezas de uma área de Tormenta.'],
    ['Adamante','Aumenta o dano em um passo.','Fornece redução de dano: RD 2.','Fornece redução de dano: RD 2.','Fornece redução de dano: RD 5.','Quando lança uma magia, você pode pagar +1 PM para rolar novamente qualquer resultado 1 na rolagem de dano dela.','Encontrado apenas em meteoritos (e por isso também chamado de "ferro-meteórico"), o adamante é um metal escuro, fosco e mais denso que o aço.'],
    ['Gelo Eterno','Causa +2 pontos de dano por frio.','Fornece redução de fogo: resistência 5.','Fornece redução de fogo: resistência 5.','Fornece redução de fogo: resistência 10.','Quando causa dano com uma magia de frio, você pode rolar novamente qualquer resultado 1.','As gélidas Montanhas Uivantes produzem gelo que nunca derrete. Expedições de aventureiros exploram essa região glacial perigosa à caça deste material fantástico.'],
    ['Madeira Tolon','Conta como mágica para vencer redução de dano. Além disso, habilidades ativadas ao se fazer um ataque ou usar a ação agredir têm seu custo em PM reduzido em -1.',,'Fornece resistência a magia +2.',,'Fornece resistência a magia +2.','A Floresta de Tollon produz um tipo de madeira negra, dura como aço e dotada de propriedades mágicas. Apenas armas de madeira — arcos, bordões, davas, lanças, piques e tacapes —, escudos leves e esotéricos podem ser feitos com madeira Tollon.'],
    ['Matéria Vermelha','Causa +1d6 de dano extra. Porém, sempre que você acerta um ataque com a arma, perde 1 ponto de vida. Lefou e lefeu são imunes tanto ao dano adicional de matéria vermelha quanto à perda de vida por usar armas desse material.','Por sua aparência "borrada", fornecem chance de falha para cada ataque: 10%. Esse efeito é cumulativo entre si. Lefeu ignoram este efeito.','Por sua aparência "borrada", fornecem chance de falha para cada ataque: 10%. Esse efeito é cumulativo entre si. Lefeu ignoram este efeito.','Por sua aparência "borrada", fornecem chance de falha para cada ataque: 25%. Esse efeito é cumulativo entre si. Lefeu ignoram este efeito.','Você e todos os seus inimigos em alcance curto sofrem -2 em testes de resistência contra efeitos mágicos.','Qualquer material de origem lefeu — desde suas garras e carapaças, até minérios e panes de estruturas encontradas em áreas de Tormenta — apresenta propriedades parecidas, sendo conhecido como "matéria vermelha". Estes itens assustadores impõem ao usuário penalidade de -2 em perícias baseadas em Carisma (exceto Intimidação).'],
    ['Mithral','Aumenta sua margem de ameaça em 1. Por exemplo, uma espada longa de mitral tem margem de ameaça 18-20.','Tem sua penalidade de armadura diminuída em 2.','Tem sua penalidade de armadura diminuída em 2.','Tem sua penalidade de armadura diminuída em 2. Armaduras pesadas de mitral permitem que você aplique até dois pontos de sua Destreza na Defesa.','Permite que você pague +2 PM ao lançar uma magia para aumentar a CD dela em +2.','Metal raro e valioso, o mitral é prateado, brilhante e mais leve que aço. Itens de mitral ocupam -1 espaço (mínimo 1).']
];

const mat_esp_valor = [
    [6000,3000,3000,6000,6000],
    [3000,6000,6000,18000,3000],
    [600,1500,1500,3000,3000],
    [600,,1500,,1500],
    [1500,6000,6000,18000,3000],
    [1500,1500,1500,12000,3000]
];

const efeitos_magicos_weap = [
    [1,5,'Ameaçadora',1,,'A margem de ameaça da arma duplica. Por exemplo, uma espada longa ameaçadora tem margem de ameaça 17. Efeitos que duplicam a margem de ameaça são aplicados antes de quaisquer efeitos que a aumentem.','Duplica margem de ameaça'],
    [6,10,'Anticriatura',1,,'A arma é letal contra um tipo de criatura (ou uma raça de humanoides). Uma vez por rodada, quando ataca uma criatura desse tipo, você pode gastar 2 PM. Se fizer isso e acenar o ataque, causa +4d8 de dano. Para determinar o tipo de criatura aleatoriamente, role 1d6: 1) animal; 2) construto; 3) espírito; 4) monstro; 5) morto-vivo; 6) uma raça de humanoides.','Bônus contra tipo de criatura'],
    [11,12,'Arremesso',1,,'A arma pode ser arremessada em alcance curto. Caso já pudesse ser arremessada, seu alcance aumenta em uma categoria. Após o ataque, se estiver livre, a arma volta voando para você. Pegá-la é uma reação.','Pode ser arremessada'],
    [13,14,'Assassina',1,,'A arma aumenta os dados de dano extra de um ataque furtivo para d8. Além disso, quando faz um Ataque Furtivo, você pode gastar 2 PM. Se fizer isso, pode rolar novamente quaisquer resultados 1 nesses dados de dano extra.','Aumenta ataque furtivo'],
    [15,16,'Caçadora',1,,'A arma persegue o alvo, anulando penalidades por camuflagem leve e total e por cobertura leve. Caso a arma seja de ataque à distância, seu alcance também aumenta em uma categoria.','Ignora camuflagem leve e total e cobertura leve'],
    [17,21,'Congelante',1,,'A arma causa +1d6 de dano de frio. Uma vez por rodada, quando ataca, você pode gastar 2 PM. Se fizer isso e acertar o ataque, a vítima fica enredada por uma rodada. Uma arma congelante é coberta por uma camada de gelo e névoa.','+1d6 de dano de frio'],
    [22,23,'Conjuradora',1,,'Um conjurador pode lançar na arma uma magia que tenha como alvo uma criatura ou que afete uma área. A magia não gera efeito na hora; em vez disso, fica guardada no item. Quando acerta um ataque com a arma, você pode descarregar a magia guardada como uma ação livre e sem pagar seu custo. Ela tem como alvo (ou como centro de sua área) a criatura ou ponto atingido pelo ataque. Uma vez que a magia seja descarregada, outra pode ser armazenada.','Pode guardar e lançar magias'],
    [24,28,'Corrosiva',1,,'A arma causa +1d6 de dano de ácido. Uma vez por rodada, quando ataca, você pode gastar 2 PM. Se fizer isso e acertar o ataque, a vítima sofre 4d4 pontos de dano de ácido na próxima rodada. Uma arma corrosiva exala vapores e goteja líquido tóxico.','+1d6 de dano de ácido'],
    [29,30,'Dançarina',1,,'Você pode gastar uma ação de movimento e 1 PM para fazer a arma flutuar e atacar uma criatura em alcance curto a sua escolha, com as mesmas estatísticas que teria se você a estivesse empunhando. Este efeito tem duração sustentada; se parar de sustentá-lo, a arma cai no chão.','Ataca sozinha'],
    [31,34,'Defensora',1,,'A arma se movimenta para aparar ataques contra você. Você recebe +2 na Defesa.','Defesa +2'],
    [35,36,'Destruidora',1,,'Se usada contra construtos e objetos (com a manobra quebrar), a arma fornece +2 no teste de ataque e causa +2d8 de dano.','Bônus contra construtos'],
    [37,38,'Dilacerante',1,,'A arma inflige ferimentos profundos. Quando faz um acerto crítico com a arma, você causa +10 pontos de dano.','+10 de dano em acertos críticos'],
    [39,40,'Drenante',1,,'Quando você faz um acerto crítico em uma criatura viva, a criatura fica fraca e você ganha 2d10 pontos de vida temporários. Uma arma drenante emite um brilho púrpura.','Crítico drena vítima'],
    [41,45,'Elétrica',1,,'A arma causa +1d6 de dano de eletricidade. Uma vez por rodada, quando ataca, você pode gastar 2 PM. Se fizer isso e acenar o ataque, um raio atinge outra criatura em alcance curto, causando 3d8 pontos de dano de eletricidade. Uma arma elétrica emite faíscas e é coberta de arcos voltaicos.','+1d6 de dano de eletricidade'],
    [46,46,'Energética',2,,'A arma tem sua parte perigosa (a lâmina de uma espada, a ponta de uma lança...) transformada em magia pura. Ela fornece +4 em testes de ataque, ignora redução de dano, converte todo o dano causado para essência e emana luz como uma tocha. Pré-requisito: formidável.','Bônus em ataque'],
    [47,48,'Excruciante',1,,'A arma inflige dor terrível. Uma criatura viva atingida fica fraca. Se já estiver fraca, fica debilitada (a condição máxima que esta arma pode causar).','Causa fraqueza'],
    [49,53,'Flamejante',1,,'A arma causa +1d6 de dano de fogo. Uma vez por rodada, quando ataca, você pode gastar 2 PM. Se fizer isso, em vez do ataque normal você dispara uma bola de fogo contra um alvo em alcance médio. O alvo sofre 6d6 pontos de dano. Um teste de Reflexos (CD For ou Des, à sua escolha) reduz à metade. Uma arma flamejante emana chamas como uma tocha.','+1d6 de dano de fogo'],
    [54,63,'Formidável',1,,'A arma é encantada para desferir golpes precisos. Ela fornece +2 em testes de ataque e rolagens de dano.','Ataque e dano +2'],
    [64,64,'Lancinante',1,,'A arma inflige ferimentos mortais. Quando faz um acerto crítico com a arma, você causa + 10 pontos de dano ou, além de multiplicar os dados de dano, multiplica também quaisquer bônus numéricos, a sua escolha. Este efeito substitui o efeito de dilacerante. Pré-requisito: dilacerante.','Causa crítico terrível'],
    [65,72,'Magnífica',2,,'A arma é encantada para desferir golpes perfeitos. Ela fornece +4 em testes de ataque e rolagens de dano. Pré-requisito: formidável.','Ataque e dano +4'],
    [73,74,'Piedosa',1,,'A arma causa +1d8 de dano, mas todo o dano causado é não letal. Você pode gastar 1 PM para desativar e ativar este encanto','Dano não letal'],
    [75,76,'Profana',1,,'A arma causa +2d8 de dano contra devotos de deuses do Bem (que canalizam apenas energia positiva) e criaturas bondosas (a critério do mestre). Uma arma profana emite luz rubra pulsaste.','Bônus contra devotos do Bem'],
    [77,78,'Sagrada',1,,'A arma causa +2d8 de dano contra devotos de deuses do Mal (que canalizam apenas energia negativa) e criaturas malignas (a critério do mestre). Uma arma sagrada emite uma sutil luz pura.','Bônus contra devotos do Mal'],
    [79,80,'Sanguinária',1,,'Uma criatura viva atingida fica sangrando. Dano de sangramento causado pela arma é cumulativo — uma criatura atingida duas vezes perde 2d6 PV por sangramento por rodada.','Causa sangramento'],
    [81,82,'Trovejante',1,,'A arma emite um trovão ribombante a cada golpe. Quando você faz um acerto critico, a vitima fica atordoada por uma rodada (Fort CD For ou Des, a sua escolha, evita). Se passar nesse teste, a criatura não pode mais ser atordoada por este efeito até o fim da cena.','Causa atordoamento'],
    [83,84,'Tumular',1,,'A arma causa +1d8 de dano de trevas. Uma vez por rodada, quando ataca, você pode gastar 2 PM. Se fizer isso, o bônus de dano aumenta para +2d8, mas você sofre 1d8 pontos de dano de trevas. Uma arma tumular drena o calor ao redor.','+1d8 de dano de trevas'],
    [85,88,'Veloz',1,,'Você recebe a habilidade Ataque Extra, do guerreiro, mas só pode usá-la com esta arma. Se já a possui, em vez disso, o custo para usá-la com esta arma diminui em -1 PM.','Fornece ataque extra'],
    [89,90,'Venenosa',1,,'Uma vez por rodada, quando ataca, você pode gastar 2 PM. Se fizer isso e acenar o ataque, a vitima fica envenenada, perdendo 1d12 pontos de vida por rodada durante 3 rodadas. Uma arma venenosa verte um liquido verde e viscoso.','Causa envenenamento'],
    [91,100,'Arma específica']
];

const efeitos_magicos_armor = [
    [1,6,'Abascanto',1,,'Você recebe resistência a magia +5.','Resistência contra magia'],
    [7,10,'Abençoado',1,,'Você recebe redução de trevas 10 e +5 em testes de resistência contra efeitos de necromancia. Um item abençoado é decorado com gravuras de símbolos sagrados de deuses do Bem.','Resistência contra trevas'],
    [11,12,'Acrobático',1,,'Você recebe +5 em Acrobacia e ignora a penalidade de armadura do item para testes dessa perícia.','Bônus em Acrobacia'],
    [13,14,'Alado',1,,'Você pode gastar 2 PM para fazer asas emergirem de suas costas e receber deslocamento de voo 12m por uma rodada Você pode gastar 1 PM no início de cada um de seus turnos para manter o efeito.','Deslocamento de voo 12m'],
    [15,16,'Animado',1,1,'Você pode gastar uma ação de movimento e 1 PM para fazer o escudo flutuar ao seu redor até o fim da cena. Você recebe o mesmo bônus na Defesa que receberia se estivesse empunhando o escudo, mas fica com as duas mãos livres. Você só pode ser protegido por um escudo ao mesmo tempo.','Escudo defende sozinho'],
    [17,18,'Assustador',1,,'Você pode gastar uma ação de movimento e 2 PM para gerar uma onda de medo. Inimigos em alcance curto devem passar num teste de Vontade (CD Car) ou ficarão abalados até o fim da cena. Um item assustador possui manchas de sangue, ossos pendurados e outras decorações horripilantes.','Causa efeito de medo'],
    [19,22,'Cáustica',1,,'Você recebe redução de ácido 10 e pode gastar uma ação de movimento e 2 PM para fazer o item gotejar ácido. Se fizer isso, seus ataques causam + 1d4 de dano de ácido até o fim da cena.','Resistência contra ácido'],
    [23,32,'Defensor',1,,'O item é encantado para desviar golpes. O bônus na Defesa do item aumenta em +2.','Defesa +2'],
    [33,34,'Escorregadio',1,,'Você recebe +10 em testes de Acrobacia para escapar e em testes de manobra contra agarrar. Um item escorregadio parece estar sempre coberto de óleo levemente gorduroso.','Bônus para escapar'],
    [35,36,'Esmagador',1,1,'Este escudo fornece +2 em ataques e dano e tem seu dano aumentado em um passo.','Escudo causa mais dano'],
    [37,38,'Fantasmagórico',1,,'Você pode lançar a magia <i>Manto de Sombras</i>. Um item fantasmagórico é cinzento e esfumaçado.','Lança Monto de Sombros'],
    [39,40,'Fortificado',1,,'Você recebe 25% de chance (para escudos) e 50% de chance (para armaduras) de ignorar o dano extra de acertos críticos e ataques furtivos.','Chance de ignorar crítico'],
    [41,44,'Gélido',1,,'Você recebe redução de frio 10 e pode gastar uma ação de movimento e 2 PM para se cobrir de gelo até o fim da cena. Se fizer isso, recebe 10 PV temporários. Um item gélido é azulado e frio ao toque.','Resistência contra frio'],
    [45,54,'Guardião',2,,'O item emite um campo de força que desvia ataques. O bônus na Defesa do item aumenta em +4. Pré-requisito: defensor.','Defesa +4'],
    [55,56,'Hipnótico',1,,'Você pode gastar uma ação padrão e 3 PM para emitir luzes coloridas. Inimigos em alcance curto devem passar num teste de Vontade (CD Car) ou ficarão fascinados por 1d6 rodadas. O efeito termina se qualquer criatura afetada for atacada. Um item hipnótico é espalhafatoso e colorido.','Causa efeito de fascinar'],
    [57,58,'Ilusório',1,,'Você pode gastar uma ação de movimento e 1 PM para fazer o item adquirir a aparência de uma roupa comum, mas mantendo suas propriedades (bônus na Defesa, penalidade de armadura...). A magia <i>Visão da Verdade</i> revela o item disfarçado.','Camufla-se como item comum'],
    [59,62,'Incandescente',1,,'Você recebe redução de fogo 10 e pode gastar uma ação de movimento e 2 PM para fazer o item emitir labaredas até o fim da cena. Se fizer isso, no início de cada um de seus turnos você causa 1d6 pontos de dano de fogo em todas as criaturas adjacentes. Um item incandescente é avermelhado e quente ao toque.','Resistência contra fogo'],
    [63,68,'Invulnerável',1,,'Você recebe redução de dano 2 (para escudos) ou 5 (para armaduras).','Redução de dano'],
    [69,72,'Opaco',1,,'Você recebe redução de ácido, eletricidade, fogo e frio 10. Um item opaco parece sem cor, totalmente comum e desinteressante.','Redução de energia'],
    [73,78,'Protetor',1,,'Você recebe +2 em testes de resistência.','Resistência +2'],
    [79,80,'Refletor',1,,'Uma vez por rodada, quando você é alvo de uma magia, pode gastar PM igual ao custo dela para refleti-la de volta ao conjurador. As características da magia (efeitos, CD...) se mantêm, mas você toma qualquer decisão exigida por ela. Um item refletor parece espelhado.','Reflete magia'],
    [81,84,'Relampejante',1,,'Você recebe redução de eletricidade 10 e pode gastar uma ação de movimento e 2 PM para gerar arcos voltaicos até o fim da cena. Se fizer isso, qualquer criatura que o ataque em corpo a corpo sofre 2d6 pontos de dano de eletricidade. Um item relampejante é decorado com ouro, prata e cobre.','Resistência contra eletricidade'],
    [85,86,'Reluzente',1,,'Você pode gastar uma ação de movimento e 2 PM para emitir um clarão de luz. Todos os inimigos em alcance curto devem passar num teste de Reflexos (CD Car) ou ficarão cegos por uma rodada. Um item reluzente é polido e brilhante.','Causa efeito de cegueira'],
    [87,88,'Sombrio',1,,'Você recebe +5 em Furtividade e ignora a penalidade de armadura do item para testes dessa perícia. Um item sombrio é escuro, fosco e bem lubrificado, para não fazer barulho.','Bônus em Furtividade'],
    [89,90,'Zeloso',1,,'Uma vez por rodada, se um aliado adjacente for alvo de um ataque, você pode gastar 1 PM para se tornar o alvo do ataque, que então é resolvido normalmente.','Atrai ataques em aliados'],
    [91,100,'Item específico']
];

const magic_weap = [
    [1,5,'Azagaia dos relâmpagos','Quando arremessada, esta azagaia se transforma em um <i>Relâmpago</i> (6d6 de dano de eletricidade numa linha com alcance médio; CD For ou Des a sua escolha). Quando atinge o fim do alcance ela volta a ser uma azagaia e cai no chão.','T$ 30.000','Azagaia'],
    [6,15,'Espada baronial','Concedidas por reis-imperadores a vassalos dignos, estas espadas longas de guarda reta fornecem +1 em testes de ataque e rolagens de dano. Este bônus aumenta em +1 se você possuir um código de conduta (de honra, do herói...), for devoto de Khalmyr ou for treinado em Nobreza. Os bônus são cumulativos — um personagem com um código de conduta, devoto de Khalmyr e treinado em Nobreza recebe +4 em ataque e dano.','T$ 30.000','Espada Longa'],
    [16,25,'Lâmina da luz','De lâmina prateada e reluzente, esta <i>espada bastarda formidável</i> é concedida a cavaleiros da Luz de honra e virtude comprovadas. Você pode gastar uma ação de movimento e 2 PM para erguer a lâmina da luz acima de sua cabeça. Se fizer isso, ela irradia luz brilhante em alcance médio até o fim da cena. Todos os inimigos dentro da luz ficam ofuscados.','T$ 45.000','Espada Bastarda*'],
    [26,30,'Lança animalesca','Espinhos e folhas vivas brotam desta <i>lança formidável</i>. Se você usar a habilidade Forma Selvagem, aplica o bônus de +2 em ataque e dano da lança animalesca em suas armas naturais.','T$ 45.000','Lança'],
    [31,35,'Maça do terror','Esta <i>maça formidável</i> é feita com um osso e um crânio e permite que você lance a magia <i>Amedrontar</i> (CD For ou Car a sua escolha). Caso já conheça a magia, o custo para lançá-la diminui em -1 PM.','T$ 45.000','Maça'],
    [36,40,'Florete fugaz','Este <i>florete formidável</i> tem o cabo e a guarda trabalhados com prata e pedrarias. Quando usa a ação agredir, você pode gastar 1 PM. Se fizer isso e acertar um critico no turno, pode fazer um ataque adicional contra a mesma criatura.','T$ 50.000','Florete'],
    [41,45,'Cajado da destruição','Este <i>bordão formidável</i> escuro e reforçado com ponteiras de metal é procurado por conjuradores de batalha. Conta como um cajado arcano. Além dos beneficios desse esotérico, quando você lança uma magia de dano, ela causa +1 ponto de dano por dado.','T$ 60.000','Bordão'],
    [46,50,'Cajado da vida','Este <i>bordão formidável</i> branco com runas prateadas é valorizado por curandeiros. Conta como um cajado arcano. Além dos beneficios desse esotérico, quando você lança uma magia de cura, ela cura +2 pontos de vida por dado.','T$ 60.000','Bordão'],
    [51,55,'Machado silvestre','O cabo e a lâmina deste <i>machado de batalha formidável</i> são cobertos de gravuras representando plantas e animais selvagens. Quando você usa o machado silvestre em um ambiente ermo e ao ar livre, causa +1d8 de dano e recebe o poder <i>Trespassar</i>. Caso já possua este poder, pode utilizá-lo sem pagar pontos de mana.','T$ 70.000','Machado de Batalha'],
    [56,60,'Martelo de Doherimm','Este <i>martelo de guerra formidável</i> é feito de pedra e aço. Quando empunhado por um anão, adquire o encanto arremesso e aumenta seu dano em +1d8 (ou +2d8 se usado contra criaturas Grandes ou maiores).','T$ 70.000','Martelo de Guerra'],
    [61,67,'Arco do poder','O arco do poder conta como um <i>arco longo formidável</i>, mas parece apenas o corpo de um arco — não tem corda e não aceita flechas. Contudo, quando você o empunha e faz o gesto de puxar a corda inexistente, o arco cria uma corda e uma flecha de energia dourada. O arco do poder é capaz de ler suas intenções, produzindo diferentes tipos de flechas energéticas a sua escolha.\n• <i>Flecha Normal</i>: 3d8 pontos de dano de essência.\n• <i>Flecha Piedosa</i>: 4d8 pontos de dano de essência não letal.\n• <i>Flecha Explosiva</i>: 3d6 pontos de dano de fogo no alvo e em todas as criaturas adjacentes a ele. Essas têm direito a um teste de Reflexos (CD Des) para reduzir o dano à metade.\n• <i>Flecha-Rede</i>: Não causa dano, mas deixa a vitima agarrada por uma rede de energia. A criatura pode se soltar passando em um teste de Força ou Acrobacia (CD 25). A rede se dissipa quando a criatura se solta ou no fim da cena.','T$ 90.000','Arco Longo'],
    [68,72,'Língua do deserto','Esta <i>cimitarra formidável</i> é originária do Deserto da Perdição. Você pode gastar uma ação de movimento e 1 PM para transformar a lâmina dela em chamas até o fim da cena. Nessa condição, o dano da arma aumenta em um passo e passa a ser do tipo fogo. Você pode gastar uma ação de movimento e 2 PM para fazer as chamas brilharem com muita força. Isso deixa os inimigos em alcance curto desprevenidos por uma rodada.','T$ 90.000','Cimitarra'],
    [73,77,'Besta explosiva','Esta <i>besta pesada formidável</i> é feita de madeira escurecida, similar a carvão. Quando usa uma besta explosiva, você pode gastar 3 PM para transformar o virote disparado por ela em uma <i>Bola de Fogo</i>. Você pode mirar esta <i>Bola de Fogo</i> em uma criatura ou em um ponto em alcance médio. No primeiro caso, faça um ataque contra o alvo. Se acertar, ele sofre o dano do disparo mais 6d6 de fogo. Além disso, todas as criaturas a até 6m do alvo sofrem 6d6 pontos de dano de fogo (Ref CD Des reduz à metade). Porém, se o ataque errar, o virote se desfaz em uma nuvem de cinzas inofensivas. No segundo caso, ela funciona como a magia de mesmo nome. Nenhum teste de ataque é necessário e todas as criaturas a 6m do ponto escolhido sofrem 6d6 pontos de dano de fogo (Ref reduz à metade).','T$ 100.000','Besta Pesada'],
    [78,82,'Punhal Sszzaazita','Esta <i>adaga assassina formidável venenosa</i> tem lâmina negra e ondulada. Você pode gastar uma ação padrão e 2 PM para transformar o punhal sszzaazita em um objeto inofensivo de tamanho similar, como uma colher ou pena. Nenhuma magia é capaz de detectar essa transformação. Transformar o punhal em arma é uma ação livre.','T$ 100.000','Adaga'],
    [83,87,'Espada sortuda','Esta <i>espada curta formidável</i> é cravejada de brilhantes. Você recebe +2 nos testes de resistência e pode gastar 3 PM para rolar novamente um teste qualquer recém realizado (apenas uma vez por teste). Se possuir o poder Sortudo, em vez disso seu custo diminui em -1 PM.','T$ 110.000','Espada Curta'],
    [88,92,'Avalanche','Este <i>machado de guerra de gelo eterno congelante formidável</i> fornece redução de fogo 10. Você pode gastar uma ação padrão e 6 PM para brandi-lo acima de sua cabeça e invocar uma tempestade de gelo que afeta alcance curto ao seu redor. Criaturas na área recebem camuflagem leve e sofrem 3d6 pontos de dano de impacto e 3d6 pontos de frio por rodada. Você não sofre os efeitos nocivos da tempestade (o dano e a chance de falha pela camuflagem) e pode gastar 1 PM no inicio de cada um de seus turnos para mantê-la.','T$ 140.000','Machado de Guerra'],
    [93,95,'Cajado do poder','Este <i>bordão defensor magnifico</i> tem cabo reto e liso, com uma joia cintilante na ponta. Conta como um cajado arcano. Além dos beneficios desse esotérico, o custo de suas magias arcanas diminui em -1 PM e a CD para resistir a elas aumenta em +2 (para um aumento total de +3).','T$ 180.000','Bordão'],
    [96,100,'Vingadora sagrada','Esta <i>espada longa formidável</i> revela todo o seu poder apenas quando empunhada por um paladino. Se você for um paladino, recebe +5 em testes de ataque e rolagens de dano, o custo de seu Golpe Divino é reduzido em -1 PM e você e seus aliados em alcance curto recebem resistência a magia +5.','T$ 200.000','Espada Longa']
];
    
    const magic_armor = [
    [1,10,'Cota élfica','Composta de anéis finíssimos, esta <i>cota de malha defensora de mitral</i> parece ser feita de seda. Ela permite que você aplique sua Destreza na Defesa como se fosse uma armadura leve.','T$ 30.000','Cota de Malha'],
    [11,20,'Couro de monstro','Usado por chefes bárbaros das Montanhas Sanguinárias, este <i>gibão de peles defensor</i> é feito do couro de monstros, corno basiliscos e serpes. Se você usar o poder Ataque Poderoso ou fizer uma investida, recebe um bônus de +2d6 nas rolagens de dano.','T$ 36.000','Gibão de Peles'],
    [21,25,'Escudo do conjurador','Este <i>escudo leve defensor</i> tem uma pequena tira de couro na parte interna, sobre a qual um conjurador pode lançar uma magia. A magia não surte efeito na hora; em vez disso, fica inscrita na tira. A tira pode então ser lida como um pergaminho. Uma vez que a magia seja lançada, outra pode ser inscrita.','T$ 45.000','Escudo Leve'],
    [26,32,'Loriga do centurião','Esta <i>loriga segmentada defensora</i> é dourada com detalhes em vermelho e possui o símbolo de Tauron, antigo Deus da Força, gravado no peitoral. Se estiver liderando uma ou mais criaturas (em termos de jogo, se estiver usando o poder Comandar ou similar), seus ataques corpo a corpo causam +2d6 de fogo.','T$ 45.000','Loriga Segmentada'],
    [33,42,'Manto da noite','Este <i>couro batido ajustado defensor sombrio</i> é negro com partes metálicas foscas. Quando usa esta armadura, você não sofre penalidade em testes de Furtividade por se mover em seu deslocamento normal e a penalidade que você sofre em testes de Furtividade por atacar diminui para -10.','T$ 45.000','Couro Batido'],
    [43,49,'Couraça do comando','Esta <i>couraça banhada a ouro sob medida defensora</i> irradia uma aura de autoridade. Você recebe +2 em Carisma. Se usar o poder Comandar, o bônus fornecido aumenta para +2.','T$ 45.000','Couraça'],
    [50,59,'Baluarte anão','Esta <i>armadura completa reforçada defensora de adamante</i> fornece proteção sem igual. Se você não se deslocar em seu turno, a RD que ela fornece aumenta para 10 até seu próximo turno.','T$ 50.000','Armadura Completa'],
    [60,66,'Escudo espinhoso','Este <i>escudo pesado defensor</i> é coberto de espinhos. Você pode gastar uma ação de movimento e 2 PM para disparar um espinho em um alvo em alcance curto. O espinho acena automaticamente e causa 1d10 +2 pontos de dano de perfuração.','T$ 50.000','Escudo Pesado'],
    [67,76,'Escudo do leão','Este <i>escudo pesado defensor</i> é forjado como uma cabeça de leão rugindo. Uma vez por rodada, você pode gastar 2 PM para fazer a cabeça criar vida e morder uma criatura adjacente. A mordida acerta automaticamente e causa 2d6+2 pontos de dano de perfuração.','T$ 50.000','Escudo Pesado'],
    [77,83,'Carapaça demoníaca','Esta <i>armadura completa macabra reforçada guardiã</i> é forjada para fazer com que seu usuário pareça um demônio — o elmo tem o formato de uma cabeça demoníaca com chifres e o usuário enxerga através da boca aberta e repleta de dentes. Se você for devoto de uma divindade do Mal, a armadura exala energia negativa, fazendo os seus ataques corpo a corpo causarem +1d8 de dano de trevas.','T$ 63.000','Armadura Completa'],
    [84,88,'Escudo do eclipse','Este <i>escudo pesado defensor</i> é completamente negro e parece absorver a luz. Ele fornece redução de trevas 10 e causa +1d8 de dano de trevas num ataque. Além disso, você pode gastar uma ação de movimento e 2 PM para lançar <i>Escuridão</i>.','T$ 70.000','Escudo Pesado'],
    [89,93,'Escudo de Azgher','Este <i>escudo pesado guardião</i> é forjado na forma de um sol estilizado. Você pode gastar uma ação padrão e 10 PM para fazê-lo emitir uma luz brilhante e quente num cone com alcance curto. A luz gera os efeitos da magia <i>Visão da Verdade</i> e causa 6d6 pontos de dano de fogo em todos os seus inimigos (mortos-vivos e criaturas vulneráveis a luz solar sofrem 6d8 pontos de dano). Você pode gastar 1 PM no início de cada um de seus turnos para manter a luz.','T$ 140.000','Escudo Pesado'],
    [94,100,'Armadura da luz','Esta <i>armadura completa banhada a ouro reforçada guardiã zelosa</i> possui o símbolo de Khalmyr gravado no peitoral. Se você possuir um código de conduta (de honra, do herói...) ou for devoto de uma divindade do Bem, recebe redução de dano igual ao seu Carisma.','T$ 150.000','Armadura Completa']
];

const magic_acess_maior = [
    [1,2,'Elmo do teletransporte','Você pode lançar <i>Salto Dimensional</i> e <i>Teletransporte</i>, mas apenas em você mesmo. Caso já conheça as magias, o custo para lançá-las diminui em -1 PM.','T$ 30.000'],
    [3,4,'Gema da telepatia','Você pode lançar <i>Compreensão</i> e <i>Enfeitiçar</i> (CD Car) sem pagar seu custo em PM.','T$ 30.000'],
    [5,9,'Gema elemental','Você pode lançar <i>Conjurar Elemental</i> sem pagar seu custo em PM.','T$ 30.000'],
    [10,15,'Tomo da saúde corporal','Este tomo volumoso contém exercícios de resistência e dietas saudáveis, mas suas palavras trazem um poderoso efeito mágico. Ler o livro leva uma semana e aumenta seu valor de   Constituição em +1 permanentemente (não cumulativo com outras leituras do livro). Assim que o livro é lido, a magia desaparece de suas páginas e ele se torna um item mundano.','T$ 30.000'],
    [16,21,'Tomo do bom exercício','Este tomo volumoso contém exercícios de musculação, mas escondido entre as palavras há um poderoso efeito mágico. Ler o livro leva uma semana e aumenta seu valor de Força em +1 permanentemente (não cumulativo com outras leituras do livro). Assim que o livro é lido, a magia desaparece de suas páginas e ele se torna um item mundano.','T$ 30.000'],
    [22,27,'Tomo dos movimentos precisos','Este tomo volumoso descreve exercícios de coordenação e equilíbrio, mas mesclado às palavras há um poderoso efeito mágico. Ler o livro leva uma semana e aumenta seu valor de  Destreza em +1 permanentemente (não cumulativo com outras leituras do livro). Assim que o livro é lido, a magia desaparece de suas páginas e ele se torna um item mundano.','T$ 30.000'],
    [28,34,'Medalhão de Lena','Quando você é reduzido a 0 ou menos PV, esta joia emite uma explosão de energia positiva que cura 100 PV (antes que você caia). Este poder só se ativa uma vez por dia.','T$ 30.000'],
    [35,40,'Tomo da compreensão','Este livro volumoso contém ensinamentos para tornar o leitor mais centrado e aguçar sua percepção, mas também possui um poderoso efeito mágico. Ler o livro leva uma semana e aumenta seu valor de Sabedoria em +1 permanentemente (não cumulativo com outras leituras do livro). Assim que o livro é lido, a magia desaparece de suas páginas e ele se torna um item mundano.','T$ 30.000'],
    [41,46,'Tomo da liderança e influência','Este livro de encadernação luxuosa contém instruções detalhadas para convencer e inspirar os demais, mas as páginas escondem um poderoso efeito mágico. Ler o livro leva uma semana e aumenta seu valor de  Carisma em +1 permanentemente (não cumulativo com outras leituras do livro). Assim que o livro é lido, a magia desaparece de suas páginas e ele se torna um item mundano.','T$ 30.000'],
    [47,52,'Tomo dos grandes pensamentos','Este livro pesado contém exercícios para aprimorar o raciocínio e a memória, mas mesclado às palavras há um poderoso efeito mágico. Ler o livro leva uma semana e aumenta seu valor de Inteligência em +1 permanentemente (não cumulativo com outras leituras do livro). Assim que o livro é lido, a magia desaparece de suas páginas e ele se torna um item mundano.','T$ 30.000'],
    [53,57,'Anel refletor','Este anel de platina é poderoso contra conjuradores. Uma vez por rodada, quando você é alvo de uma magia, pode gastar PM igual ao custo dela para refleti-la de volta ao seu conjurador. As características da magia (efeitos, CD...) se mantêm, mas você toma qualquer decisão exigida por ela.','T$ 51.000'],
    [58,60,'Cinto do campeão','Este cinturão de ouro é cravejado de joias e possui gravuras de gladiadores e pugilistas minotauros. Você recebe +1 em Força e a habilidade Briga (veja a página 76). Caso já a possua, seu dano desarmado será calculado como se você possuísse quatro níveis de lutador a mais (máximo 2d12). Por fim, caso possua o poder Torcida, o bónus que você recebe por ele aumenta para +3. Em tempos antigos, estes cintos eram dados aos vencedores dos jogos gladiatoriais do Império de Tauron. A cada ano, diversos combatentes de toda Arton viajavam a Tiberus para competir e ter uma chance de ganhar um destes itens','T$ 51.000'],
    [61,67,'Colar guardião','Este diamante lapidado preso em uma corrente de platina deflete ataques contra seu usuário. Você recebe +5 na Defesa','T$ 51.000'],
    [68,72,'Estatueta animista','Esta esta atueta de pedra é esculpida na forma de um animal. Quando é atirada no chão e a palavra de comando é proferida, transforma-se no animal correspondente. O animal fornece os benefícios de um parceiro veterano até o fim da cena, quando então volta à sua forma de estatueta. O tipo de parceiro é definido pelo animal: raposa (ajudante; perícias definidas na fabricação do item), onça (assassino), águia (atirador), lobo (combatente), leão (fortão) ou urso (guardião).','T$ 51.000'],
    [73,77,'Anel da liberdade','Forjado em ouro, este anel é uma relíquia da Igreja de Valkaria. Você fica permanentemente sob efeito de <i>Libertação</i>.','T$ 60.000'],
    [78,82,'Tapete voador','Com um comando, este tapete flutua, fornecendo deslocamento de voo 12m. O tapete tem 3m x 3m e pode carregar seis criaturas Médias (ou 120 espaços). Se você estiver em alcance longo do tapete, pode comandar o voo dele.','T$ 60.000'],
    [83,87,'Braceletes de ouro','Estes braceletes protegem seu usuário com um campo de força invisível, porém tangível. Você recebe +8 na Defesa, cumulativo com outros itens mágicos, mas não com armaduras.','T$ 64.500'],
    [88,89,'Espelho da oposição','Este item lembra um espelho normal com cerca de 1m de comprimento e 1,5m de altura. Pode ser fixado em qualquer superfície e ativado (ou desativado) com um comando. Quando uma criatura observa seu reflexo, o espelho cria uma cópia sua, com as mesmas habilidades e equipamento. A duplicata ataca a criatura original; quando um dos dois é derrotado, a duplicata e seus itens desaparecem.','T$ 75.000'],
    [90,94,'Robe do arquimago','Este traje pesado alinha-se com as energias arcanas emitidas por seu usuário para gerar um campo protetor. Se você for um conjurador arcano, recebe um bônus na Defesa igual a 5 + o círculo de magia mais alto que puder lançar e um bônus em testes de resistência igual à metade do bônus na Defesa. Assim, um arcanista de 9° nível (capaz de lançar magias de 3° círculo) recebe +8 na Defesa e +4 em testes de resistência.','T$ 90.000'],
    [95,96,'Orbe das tempestades','Esta esfera de vidro com 20cm de diâmetro contém fumaça e raios em seu interior. Você pode lançar <i>Controlar o Clima</i> e <i>Fúria do Panteão</i> (CD Sab). Caso já conheça as magias, o custo para lançá-las diminui em -1 PM. Além disso, você e todos os seus aliados adjacentes ficam sob efeito de <i>Suporte Ambiental</i>.','T$ 97.500'],
    [97,98,'Anel da regeneração','Você recebe Cura Acelerada 5. Os efeitos do anel só se ativam após um dia de uso.','T$ 150.000'],
    [99,100,'Espelho do aprisionamento','Este item de cristal, com 1,5m de altura e moldura de metal, pode ser fixado em qualquer superfície e ativado (ou desativado) com um comando. Qualquer criatura que se aproxime a alcance curto do espelho do aprisionamento e enxergue seu próprio reflexo deve passar em um teste de Reflexos (CD Int) ou será transportada magicamente para um espaço extradimensional dentro do espelho, ficando presa ali. O tamanho da criatura não importa — mas construtos, mortos-vivos e objetos não podem ser transportados. Com um comando, é possível conversar com uma criatura presa no espelho ou libertá-la. Se o espelho for quebrado, todas as criaturas dentro dele são libertadas.','T$ 150.000']
];
    
    const magic_acess_medio = [
    [1,4,'Anel de telecinesia','Você pode lançar <i>Telecinesia</i> (CD Int). Caso já conheça a magia, o custo para lançá-la diminui em -1 PM.','T$ 10.500'],
    [5,8,'Bola de cristal','Esta pequena esfera revela pessoas e lugares distantes. Olhar através dela é uma ação completa e gera a magia <i>Vidência</i> (CD Sab).','T$ 10.500'],
    [9,10,'Caveira maldita','Esta pedra esculpida em formato de crânio gera permanentemente o efeito da magia <i>Profanar</i>, com o próprio crânio como ponto de origem. Mortos-vivos e devotos de deuses do Mal na área de efeito recebem +2 em testes e Defesa.','T$ 10.500'],
    [11,14,'Botas aladas','Você pode gastar 2 PM para fazer asas brotarem dos calcanhares destas botas e receber deslocamento de voo 12m por uma rodada. Você pode gastar 1 PM no início de cada um de seus turnos para manter esse efeito.','T$ 15.000'],
    [15,18,'Braceletes de bronze','Estes braceletes protegem seu usuário com um campo de força invisível, porém tangível. Você recebe +4 na Defesa, cumulativo com outros itens mágicos, mas não com armaduras.','T$ 16.500'],
    [19,24,'Anel da energia','Você recebe +5 PM. Os efeitos do anel só se ativam após um dia de uso.','T$ 21.000'],
    [25,30,'Anel da vitalidade','Você recebe +10 PV. Os efeitos do anel só se ativam após um dia de uso.','T$ 21.000'],
    [31,34,'Anel de invisibilidade','Ao colocar este anel de prata, você fica sob efeito de <i>Invisibilidade</i>. O efeito termina se você fizer um ataque ou lançar uma magia ofensiva, mas você pode tirar e recolocar o anel (uma ação padrão) para que ele volte a funcionar.','T$ 21.000'],
    [35,38,'Braçadeiras do arqueiro','Estes protetores de punho fornecem +2 em rolagens de dano com armas de ataque à distância.','T$ 21.000'],
    [39,42,'Brincos de Marah','Este par de brincos brancos é abençoado pela Deusa da Paz. A primeira criatura que o atacar em uma cena deve fazer um teste de Vontade (CD Car). Se falhar, perderá a ação. Se você atacar uma criatura, o efeito dos brincos é cancelado por um dia. Se você possuir Aparência Inofensiva (ou um poder similar) os efeitos acumulam, afetando as duas primeiras criaturas que o atacarem em uma cena.','T$ 21.000'],
    [43,46,'Faixas do pugilista','Estas faixas de pano surrado são amarradas nos punhos, nos braços ou na testa. Você recebe +2 em testes de ataque e rolagens de dano com ataques desarmados.','T$ 21.000'],
    [47,50,'Manto da aranha','Este manto é feito de seda negra com fios de prata bordados. Você recebe deslocamento de escalada igual ao seu deslocamento terrestre, +5 em testes de resistência contra venenos e imunidade a teias mundanas ou mágicas. Além disso, pode lançar <i>Teia</i> (CD Des). Caso já conheça a magia, o custo para lançá-la diminui em -1 PM.','T$ 21.000'],
    [51,54,'Vassoura voadora','Com um comando, esta vassoura flutua, fornecendo deslocamento de voo 12m. Pode carregar 2 criaturas médias (ou 40 espaços). Se você estiver em alcance longo da vassoura, pode comandar o voo dela.','T$ 21.000'],
    [55,58,'Símbolo abençoado','Um colar com o símbolo de um dos deuses do Panteão, feito de metal para resistir a viagens e aventuras. Se você for devoto desse deus, o custo de suas magias divinas diminui em -1 PM. Apenas inventores devotos do deus em questão podem fabricar um símbolo abençoado.','T$ 21.000'],
    [59,64,'Amuleto da robustez','Este disco dourado é ligado a uma corrente de ouro e usado como um colar. Você recebe +2 em Constituição.','T$ 25.500'],
    [65,68,'Botas velozes','Você recebe +3m em seu deslocamento e pode lançar <i>Velocidade</i> (apenas sobre você mesmo).','T$ 25.500'],
    [69,74,'Cinto da força do gigante','Este cinto largo é feito de couro com rebites de ferro. Você recebe +2 em Força.','T$ 25.500'],
    [75,80,'Coroa majestosa','Esta coroa de ouro possui dezenas de pedras preciosas. Você recebe +2 em Carisma','T$ 25.500'],
    [81,86,'Estola da serenidade','Esta faixa de pano com inscrições mágicas é usada sobre a nuca, com as duas extremidades caindo paralelas na frente do corpo. Você recebe +2 em Sabedoria.','T$ 25.500'],
    [87,88,'Manto do morcego','Este manto marrom escuro ou negro fornece +5 em Furtividade e permite que você fique pendurado de ponta-cabeça no teto, como um morcego. Além disso, você pode gastar uma ação padrão para segurar as pontas do manto e se transformar em um morcego. Seu tamanho muda para Minúsculo e você recebe deslocamento de voo 12m e uma arma natural de mordida (dano 1d4, perfuração). Em outros aspectos, isso funciona como a Forma Selvagem do druida. Você só pode se transformar em morcego à noite ou em ambientes escuros.','T$ 25.500'],
    [89,94,'Pulseiras da celeridade','Esta pulseira de platina aguça todos os seus movimentos. Você recebe +2 em Destreza.','T$ 25.500'],
    [95,100,'Tiara da sapiência','Esta tiara delicada possui uma gema que descansa sobre a testa. Você recebe +2 em Inteligência (mas não recebe perícias treinadas extras).','T$ 25.500']
];

const magic_acess_menor = [
    [1,2,'Anel do sustento','Você não precisa comer ou beber e precisa dormir apenas duas horas por noite para descansar. Os efeitos do anel só se ativam após uma semana de uso.','T$ 3000'],
    [3,7,'Bainha mágica','Esta bainha de couro curtido e prata muda de tamanho para acomodar qualquer arma corpo a corpo. Você pode lançar <i>Arma Mágica</i> em qualquer arma na bainha sem pagar seu custo em PM.','T$ 3000'],
    [8,12,'Corda da escalada','Esta corda de 15m é bastante fina, mas forte o suficiente para suportar até seis criaturas médias (ou 120 espaços). Com um comando (uma ação de movimento), a corda se move em qualquer direção (incluindo para cima) a 3m por rodada, fixando-se firmemente onde você quiser. Ela pode se desamarrar e voltar da mesma forma.','T$ 3000'],
    [13,14,'Ferraduras da velocidade','Este conjunto de ferraduras pode ser fixado nos cascos de um cavalo (ou outro parceiro montaria, a critério do mestre) para aumentar seu deslocamento em +3m.','T$ 3000'],
    [15,19,'Garrafa da fumaça eterna','Quando a tampa desta ânfora de metal é retirada, uma grande quantidade de fumaça é liberada, gerando o efeito da magia <i>Névoa</i>. A fumaça persiste até a garrafa ser tampada. Após isso, dissipa-se no fim da cena (ou após 4 rodadas, sob vento forte, ou 1 rodada, sob um vendaval).','T$ 3000'],
    [20,24,'Gema da luminosidade','Este cristal tem a aparência de um longo prisma. Com um comando, emite luz equivalente a uma tocha ou então um raio brilhante, que deixa uma criatura em alcance curto cega por 1d4 rodadas (Fort CD Car evita).','T$ 3000'],
    [25,29,'Manto élfico','Indistinguível de um manto cinza comum. Entretanto, quando usado com o capuz cobrindo o rosto, fornece +5 em Furtividade.','T$ 3000'],
    [30,34,'Mochila de carga','Este item, que parece uma simples mochila de pano, está na verdade ligado a um espaço interdimensional — fazendo com que seja maior por dentro do que por fora. A mochila de carga aumenta sua capacidade de carga em 10 espaços (ela própria não gasta um espaço). Se a mochila for rasgada, os objetos em seu interior são destruídos. Criaturas vivas colocadas no inte-ior da mochila podem sobreviver até 10 minutos, mas depois disso ficarão sem ar.','T$ 3000'],
    [35,40,'Brincos da sagacidade','Este par de brincos de safira aguça o raciocínio. Você recebe +2 em Inteligência (mas não recebe perícias treinadas extras).','T$ 4500'],
    [41,46,'Luvas da delicadeza','Estas luvas de tecido fino permitem manipulação delicada. Você recebe +1 em Destreza.','T$ 4500'],
    [47,52,'Manoplas da força do ogro','Este par de luvas é feito de couro grosso com rebites de ferro. Você recebe +1 em Força.','T$ 4500'],
    [53,59,'Manto da resistência','Este manto de tecido grosso e pesado protege seu usuário. Você recebe +2 em testes de resistência.','T$ 4500'],
    [60,65,'Manto do fascínio','Este manto de veludo possui bordados de ouro. Você recebe +1 em Carisma.','T$ 4500'],
    [66,71,'Pingente da sensatez','Esta pequena pérola é ligada a uma corrente leve e usada como um colar. Você recebe +1 em Sabedoria.','T$ 4500'],
    [72,77,'Torque do vigor','O acabamento deste colar ou bracelete remete a um animal poderoso, como um urso ou lobo. Você recebe +1 em Constituição.','T$ 4500'],
    [78,22,'Chapéu do disfarce','Você pode lançar <i>Disfarce Ilusório</i> (CD Car), com o aprimoramento que inclui odores e sensações e muda o bônus em Enganação para disfarces para +20, sem pagar seu custo em PM. Você não pode usar outros aprimoramentos. Como parte do disfarce, o chapéu pode mudar para um elmo, faixa, tiara, gorro, touca e assim por diante.','T$ 6000'],
    [83,84,'Flauta fantasma','Você pode lançar <i>Esculpir Sons</i> (CD Car) sem pagar seu custo em PM. Você só pode usar a flauta fantasma se for treinado em Atuação.','T$ 6000'],
    [85,89,'Lanterna da revelação','Este item funciona como um lampião normal, mas sua luz revela todas as criaturas e objetos invisíveis em alcance curto.','T$ 6000'],
    [90,96,'Anel da proteção','Este anel desvia ataques contra seu usuário. Você recebe +2 de Defesa.','T$ 9000'],
    [97,98,'Anel do escudo mental','Você recebe imunidade a magias de adivinhação.','T$ 9000'],
    [99,100,'Pingente da saúde','O usuário desta joia verde em um cordão de prata recebe imunidade a doenças e venenos. Os efeitos só se ativam após uma semana de uso.','T$ 9000']
];